Repository CityOfDetroit/bloom, pull requests merged in 2021-07, with the labels that each got.

#137 Use https in the Dockerfile for the backend site.
  Dockerfile.sites-partners
  Dockerfile.sites-public
Labels: bug, epic: deployment

#184 Partner portal edit button removal for non-admin
  sites/partners/pages/index.tsx
  sites/partners/src/listings/Aside.tsx
Labels: M7, epic: partner portal

#213 [Eligibility Questionnaire] Style updates
  sites/public/pages/eligibility/age.tsx
  sites/public/pages/eligibility/bedrooms.tsx
  sites/public/pages/eligibility/disability.tsx
  sites/public/tailwind.config.js
Labels: epic: eligibility questionnaire

#214 [Eligibility Questionnaire] Add income and section 8 pages
  sites/public/pages/eligibility/income.tsx
  sites/public/pages/eligibility/section8.tsx
  ui-components/src/locales/general.json
Labels: epic: eligibility questionnaire

#242 [Eligibility Questionnaire][Accessibility] Group and label radio buttons and checkboxes
  sites/public/pages/eligibility/bedrooms.tsx
  sites/public/pages/eligibility/disability.tsx
  sites/public/pages/eligibility/section8.tsx
Labels: epic: eligibility questionnaire

#222 Allow frontend filtering by neighborhood
  sites/public/lib/hooks.ts
  sites/public/pages/listings.tsx
  ui-components/src/locales/general.json
Labels: epic: filtering

#256 Consolidate filter definitions
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.service.spec.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/shared/dto/filter.dto.ts
  backend/core/src/shared/filter/index.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/hooks.ts
  sites/public/pages/listings.tsx
  ui-components/src/locales/general.json
Labels: epic: filtering

#257 Update addFilter to take a map of filter type to field name
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.service.spec.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/shared/dto/filter.dto.ts
  backend/core/src/shared/filter/index.ts
  sites/public/pages/listings.tsx
Labels: epic: filtering

#261 [Eligibility Questionnaire] Style updates to the eligibility questionnaire
  sites/public/pages/eligibility/age.tsx
  sites/public/pages/eligibility/bedrooms.tsx
  sites/public/pages/eligibility/disability.tsx
  sites/public/pages/eligibility/income.tsx
  sites/public/pages/eligibility/section8.tsx
  sites/public/pages/eligibility/welcome.tsx
  sites/public/styles/overrides.scss
Labels: epic: eligibility questionnaire

#260 Support filtering via url params
  sites/public/lib/hooks.ts
  sites/public/pages/listings.tsx
Labels: M8, epic: filtering

#271 Move where clauses and pagination to subquery, so filtered results return all listing data
  CHANGELOG.md
  backend/core/src/listings/listings.service.spec.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/shared/dto/filter.dto.ts
  backend/core/src/shared/filter/index.ts
Labels: M8, epic: filtering

#275 [Site Set Up] Update site fonts, text weight and color, logo sizes, and partner portal logo text
  .travis.yml
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/styles/overrides.scss
  sites/partners/tailwind.config.js
  sites/public/styles/overrides.scss
  sites/public/tailwind.config.js
Labels: epic: eligibility questionnaire, epic: styling + layout

#289 Override primary button hover styles
  sites/partners/styles/overrides.scss
  sites/public/styles/overrides.scss
Labels: epic: styling + layout
