Repository CityOfDetroit/bloom, pull requests merged in 2022-06, with the labels that each got.

#1299 fix: netlify oom build issues
  sites/partners/netlify.toml
  sites/public/netlify.toml
Labels: needs review(s)

#1300 feat: automatically set region based on neighborhood
  shared-helpers/__tests__/filters.test.ts
  shared-helpers/index.ts
  shared-helpers/src/filters.ts
  shared-helpers/src/regions.ts
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/public/lib/filterUrlLink.tsx
  sites/public/lib/hooks.ts
  sites/public/pages/account/favorites.tsx
  sites/public/pages/index.tsx
  sites/public/pages/listings.tsx
  sites/public/pages/listings/filtered.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/index.ts
  ui-components/src/helpers/regionNeighborhoodMap.ts
Labels: needs review(s)

#1288 fix: scrollTo fix to pagination
  ui-components/src/global/vendor/AgPagination.tsx
Labels: ready to merge

#1297 1086/partner cypress tests
  .travis.yml
  sites/partners/cypress/fixtures/listing.json
  sites/partners/cypress/integration/application.spec.ts
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/cypress/integration/mfa.spec.ts
  sites/partners/cypress/integration/paperApplication.spec.ts
  sites/partners/cypress/support/commands.js
  sites/partners/cypress/support/index.d.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationAddress.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
  sites/partners/src/listings/PaperListingForm/UnitsSummaryAmiForm.tsx
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  ui-components/src/forms/Textarea.tsx
Labels: needs review(s)

#1304 fix: region and variable naming update
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/migration/1649062179928-add-property-region.ts
  backend/core/src/migration/1654549186207-region-rename.ts
  backend/core/src/property/types/region-enum.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/filters.ts
  shared-helpers/src/regions.ts
  sites/public/src/forms/filters/FilterForm.tsx
Labels: needs review(s)

#1307 feat: adding new features and fixing labelling
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/entities/listing-features.entity.ts
  backend/core/src/listings/types/listing-filter-keys-enum.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/migration/1654190736229-new-accessibility-features.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/filters.ts
  shared-helpers/src/formKeys.ts
  sites/public/lib/EligibilityContext.tsx
  sites/public/pages/eligibility/accessibility.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: ready to merge

#1309 1291/partners clean up
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/public/src/ListingView.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: ready to merge

#1319 1292/rent by percent of income survives filtering
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/query-filter/index.ts
Labels: ready to merge

#1332 feat: adds partners redirect
  sites/partners/netlify.toml
Labels: ready to merge

#1334 1330/fixing forgot password redirect
  sites/public/pages/reset-password.tsx
Labels: ready to merge

#1335 1329/translation update for forgot password email
  backend/core/src/migration/1655157754482-updating-forgot-password-email.ts
Labels: needs review(s)

#1346 2022-06-16 release
  backend/core/scripts/import-regions.ts
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/entities/listing-features.entity.ts
  backend/core/src/listings/types/listing-filter-keys-enum.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/migration/1654190736229-new-accessibility-features.ts
  backend/core/src/migration/1655157754482-updating-forgot-password-email.ts
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/query-filter/index.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/filters.ts
  shared-helpers/src/formKeys.ts
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/netlify.toml
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/public/lib/EligibilityContext.tsx
  sites/public/pages/eligibility/accessibility.tsx
  sites/public/pages/reset-password.tsx
  sites/public/src/ListingView.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: needs review(s), ready to merge

#1345 1311/adding utility options
  backend/core/src/listings/dto/listing-utilities.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing-utilities.entity.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
  backend/core/src/migration/1655243355949-add-utilities.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10145.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10147.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10151.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10153.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10154.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10155.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10157.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10158.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10159.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10168.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10169.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10202.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/formKeys.ts
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailAdditionalFees.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/AdditionalFees.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/AdditionalFees.test.tsx
  ui-components/src/blocks/InfoCard.scss
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
  ui-components/src/page_components/listing/AdditionalFees.stories.tsx
  ui-components/src/page_components/listing/AdditionalFees.tsx
Labels: ready to merge

#1355 1322/section 8 filtering clean
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/dto/listing-filter-params.ts
  backend/core/src/listings/types/listing-filter-keys-enum.ts
  backend/core/src/listings/views/config.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/filters.ts
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: needs review(s)

#1354 1321/listing section 8 details clean
  sites/public/src/ListingView.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: needs review(s)

#1359 fix: update gitignore and github workflows
  .github/workflows/pre-release_components.yml
  .gitignore
Labels: ready to merge

#1360 fix: changed waitlist status default to open
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
Labels: ready to merge

#1361 1314/copy updates unit group partners
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingForm/index.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#1366 fix: corrected string to match JSON
  sites/partners/src/listings/PaperListingForm/index.tsx
Labels: needs review(s)

#1364 1338/sro removal
  backend/core/src/applications/services/application-csv-exporter.service.ts
  backend/core/src/migration/1656457788192-remove-SRO.ts
  backend/core/test/unit-types/unit-types.e2e-spec.ts
  shared-helpers/__tests__/occupancyFormatting.test.tsx
  shared-helpers/__tests__/unitTypes.test.ts
  shared-helpers/src/filters.ts
  shared-helpers/src/formKeys.ts
  shared-helpers/src/unitTypes.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)
