Repository CityOfDetroit/bloom, pull requests merged in 2022-07, with the labels that each got.

#1386 2819/get assistance page
  sites/public/layouts/application.tsx
  sites/public/pages/additional-resources.tsx
  sites/public/pages/get-assistance.tsx
  sites/public/pages/housing-basics.tsx
  sites/public/src/ResourceLinkCard.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#1370 1337/homepage coming soon
  sites/public/pages/index.module.scss
  sites/public/pages/index.tsx
  sites/public/styles/listings.scss
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: ready to merge

#1393 refactor: remove rental assistance section
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#1387 1344/prominent filter button
  sites/public/pages/listings.tsx
  sites/public/pages/listings/filtered.tsx
  ui-components/package.json
  ui-components/src/actions/Button.stories.tsx
  ui-components/src/actions/Button.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/icons/FontAwesome.stories.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/notifications/ApplicationStatus.tsx
  ui-components/src/page_components/listing/ListingsGroup.tsx
  yarn.lock
Labels: ready to merge

#1401 fix: hide management section if there is no data
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#1400 fix: icon changes color on hover
  ui-components/src/actions/Button.tsx
Labels: ready to merge

#1406 feat: add the last updated column
  backend/core/src/listings/views/config.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/index.tsx
Labels: wip
