Repository CityOfDetroit/bloom, pull requests merged in 2022-05, with the labels that each got.

#1220 fix: content update
  ui-components/src/locales/general.json
Labels: needs review(s)

#1221 style: listing page rtl css changes
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/blocks/ImageCard.scss
Labels: needs review(s)

#1222 Detroit public filter fixes
  backend/core/src/listings/dto/listing-filter-params.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/query-filter/index.ts
  sites/public/pages/listings/filtered.tsx
  ui-components/src/helpers/filters.ts
Labels: needs review(s), needs changes

#1181 1090/resources page
  sites/public/layouts/application.tsx
  sites/public/page_content/locale_overrides/general.json
  sites/public/page_content/resources/civil_rights_inclusion_opportunity.md
  sites/public/page_content/resources/enforce_property_conditions.md
  sites/public/page_content/resources/eviction_prevention.md
  sites/public/page_content/resources/fair_housing.md
  sites/public/page_content/resources/financial_counseling.md
  sites/public/page_content/resources/home_repair.md
  sites/public/page_content/resources/homelessness_services.md
  sites/public/page_content/resources/homeowner_property_tax_relief.md
  sites/public/page_content/resources/housing_and_revitalization.md
  sites/public/page_content/resources/housing_commission.md
  sites/public/page_content/resources/housing_counseling.md
  sites/public/page_content/resources/housing_network.md
  sites/public/page_content/resources/housing_relocation_assistance.md
  sites/public/page_content/resources/land_bank_authority.md
  sites/public/page_content/resources/michigan_211.md
  sites/public/page_content/resources/project_clean_slate.md
  sites/public/page_content/resources/sidebar.md
  sites/public/page_content/resources/tax_foreclosure_prevention.md
  sites/public/page_content/resources/utilities_assistance.md
  sites/public/pages/additional-resources.tsx
  sites/public/src/RenderIf.tsx
  sites/public/src/Resource.tsx
  sites/public/styles/headers.scss
  sites/public/styles/listings.scss
  sites/public/styles/overrides.scss
Labels: needs changes

#1228 2022-05-03 sync main
  backend/core/src/applications/services/applications.service.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/migration/1612262618223-add-csv-formatting-type-to-listing.ts
  backend/core/src/migration/1634268265134-add-indexes-to-applications-and-householdmembers.ts
  backend/core/src/migration/1646350628943-detroitAmiCharts.ts
  backend/core/src/migration/1646422264825-addCommunityPrograms.ts
  backend/core/src/migration/1646642069064-add-new-listing-accessibility-features.ts
  backend/core/src/migration/1646872355286-catch-up.ts
  backend/core/src/migration/1646908736734-make-unit-group-ami-level-ami-percentage-optional.ts
  backend/core/src/migration/1648548425458-add-listing-marketing.ts
  backend/core/src/migration/1649062179928-add-property-region.ts
  backend/core/src/migration/1649709708991-detroit-email-updates.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10147.ts
  backend/core/src/shared/query-filter/custom-filters.ts
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/units-transformations.ts
  backend/core/test/listings/listings.e2e-spec.ts
  shared-helpers/__tests__/occupancyFormatting.test.tsx
  sites/public/layouts/application.tsx
  sites/public/page_content/resources/civil_rights_inclusion_opportunity.md
  sites/public/page_content/resources/enforce_property_conditions.md
  sites/public/page_content/resources/eviction_prevention.md
  sites/public/page_content/resources/fair_housing.md
  sites/public/page_content/resources/financial_counseling.md
  sites/public/page_content/resources/home_repair.md
  sites/public/page_content/resources/homelessness_services.md
  sites/public/page_content/resources/homeowner_property_tax_relief.md
  sites/public/page_content/resources/housing_and_revitalization.md
  sites/public/page_content/resources/housing_commission.md
  sites/public/page_content/resources/housing_counseling.md
  sites/public/page_content/resources/housing_network.md
  sites/public/page_content/resources/housing_relocation_assistance.md
  sites/public/page_content/resources/land_bank_authority.md
  sites/public/page_content/resources/michigan_211.md
  sites/public/page_content/resources/project_clean_slate.md
  sites/public/page_content/resources/tax_foreclosure_prevention.md
  sites/public/page_content/resources/utilities_assistance.md
  sites/public/pages/listings.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/__tests__/blocks/Tooltip.test.tsx
  ui-components/flattened-keys.json
  ui-components/src/blocks/InfoCard.tsx
  ui-components/src/blocks/Tooltip.scss
  ui-components/src/blocks/Tooltip.stories.tsx
  ui-components/src/global/blocks.scss
  ui-components/src/headers/SiteHeader.scss
  ui-components/src/icons/Icon.stories.tsx
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/notifications/ApplicationStatus.stories.tsx
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/text/Description.scss
  ui-components/src/text/Description.tsx
  ui-components/src/text/Tag.scss
Labels: needs review(s)

#1233 1188/terms and conditions
  sites/partners/layouts/index.tsx
  sites/public/cypress/integration/navigation.ts
  sites/public/layouts/application.tsx
  sites/public/page_content/disclaimer.md
  sites/public/page_content/terms.md
  sites/public/pages/terms.tsx
  ui-components/src/global/markdown.scss
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
  ui-components/src/locales/vi.json
  ui-components/src/locales/zh.json
Labels: needs review(s)

#1238 fix: add missing translations
  sites/partners/page_content/locale_overrides/ar.json
  sites/partners/page_content/locale_overrides/bn.json
  sites/partners/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/ar.json
  sites/public/page_content/locale_overrides/bn.json
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: needs review(s)

#1240 1014/remap neighborhood fix
  backend/core/src/listings/dto/listing-create.dto.ts
  backend/core/src/listings/dto/listing-update.dto.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/migration/1651740223899-remove-region-from-listing.ts
  backend/core/types/src/backend-swagger.ts
Labels: needs review(s)

#1241 1234/minor copy updates
  sites/public/src/ListingView.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1242 fix: updated privacy policy
  sites/public/page_content/privacy_policy.md
Labels: needs review(s)

#1237 fix: add new google translate strings
  backend/core/src/translations/services/translations.service.ts
  shared-helpers/src/formKeys.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/public/src/ListingView.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: ready to merge

#1229 1194/tooltip bug
  ui-components/src/blocks/Tooltip.tsx
Labels: needs review(s)

#1232 feat: adds sorting to partners listing grid
  backend/core/src/listings/dto/listings-query-params.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/types/listing-orderby-enum.ts
  backend/core/src/shared/types/orderdir-enum.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/hooks.ts
  sites/partners/pages/index.tsx
Labels: needs review(s)

#1259 fix: add missing translations
  sites/public/layouts/application.tsx
  sites/public/lib/helpers.tsx
  sites/public/page_content/locale_overrides/ar.json
  sites/public/page_content/locale_overrides/bn.json
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  sites/public/page_content/resources/video_affordable_housing.md
  sites/public/page_content/resources/video_housing_application.md
  sites/public/page_content/resources/video_housing_waitlists.md
  sites/public/page_content/resources/video_income_restrictions.md
  sites/public/src/ListingView.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  sites/public/styles/headers.scss
  ui-components/src/headers/SiteHeader.scss
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: needs review(s)

#1260 feat: add new hero image
  sites/public/pages/index.tsx
  sites/public/public/images/hero-main.jpg
  sites/public/public/images/hero-placeholder.jpg
Labels: ready to merge

#1261 style: change primary color from blue to green
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/tailwind.config.js
Labels: needs review(s)

#1273 fix: min max rent inputs have type number, and padding fix on error
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/src/global/forms.scss
Labels: ready to merge

#1268 1252/mobile fixes
  sites/public/lib/helpers.tsx
  sites/public/pages/_app.tsx
Labels: ready to merge

#1275 feat: update terms copy
  sites/public/page_content/locale_overrides/ar.json
  sites/public/page_content/locale_overrides/bn.json
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  sites/public/page_content/terms.md
Labels: needs review(s)

#1274 1243/filter form accessibility
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/__tests__/blocks/ImageCard.test.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/forms/FieldGroup.stories.tsx
  ui-components/src/forms/FieldGroup.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#1282 fix: remove duplicated sections
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#1270 1165/design items
  sites/public/pages/listing/[id]/[slug].tsx
  sites/public/src/ListingView.tsx
  sites/public/styles/footers.scss
  sites/public/styles/headers.scss
  ui-components/index.ts
  ui-components/src/blocks/Tooltip.scss
  ui-components/src/footers/SiteFooter.scss
  ui-components/src/navigation/LanguageNav.scss
  ui-components/src/page_components/listing/ListingDividerLine.tsx
  ui-components/src/sections/FooterSection.scss
Labels: ready to merge

#1283 1226/casing
  sites/public/lib/helpers.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1279 1248/mobile scroll issue
  package.json
  ui-components/package.json
  ui-components/src/overlays/Overlay.tsx
  yarn.lock
Labels: needs review(s)

#1257 test: public cypress tests
  .travis.yml
  sites/public/cypress/integration/eligibility-questionnaire.ts
  sites/public/cypress/integration/listing-detail.spec.ts
  sites/public/cypress/integration/navigation.spec.ts
  sites/public/cypress/integration/navigation.ts
  sites/public/cypress/integration/pages/ListingPage.ts
  sites/public/cypress/integration/pages/application/contact/address.spec.ts
  sites/public/cypress/integration/pages/application/contact/alternate-contact-contact.spec.ts
  sites/public/cypress/integration/pages/application/contact/alternate-contact-name.spec.ts
  sites/public/cypress/integration/pages/application/contact/alternate-contact-type.spec.ts
  sites/public/cypress/integration/pages/application/contact/name.spec.ts
  sites/public/cypress/integration/pages/application/financial/income.spec.ts
  sites/public/cypress/integration/pages/application/financial/vouchers.spec.ts
  sites/public/cypress/integration/pages/application/household/ada.spec.ts
  sites/public/cypress/integration/pages/application/household/add-members.spec.ts
  sites/public/cypress/integration/pages/application/household/expecting-changes.spec.ts
  sites/public/cypress/integration/pages/application/household/live-alone.spec.ts
  sites/public/cypress/integration/pages/application/household/member.spec.ts
  sites/public/cypress/integration/pages/application/household/members-info.spec.ts
  sites/public/cypress/integration/pages/application/household/preferred-units.spec.ts
  sites/public/cypress/integration/pages/application/household/programs.spec.ts
  sites/public/cypress/integration/pages/application/household/student.spec.ts
  sites/public/cypress/integration/pages/application/preferences/general.spec.ts
  sites/public/cypress/integration/pages/application/review/confirmation.spec.ts
  sites/public/cypress/integration/pages/application/review/demographics.spec.ts
  sites/public/cypress/integration/pages/application/review/summary.spec.ts
  sites/public/cypress/integration/pages/application/review/terms.spec.ts
  sites/public/cypress/integration/pages/housing-counselors.spec.ts
  sites/public/cypress/integration/pages/my-applications.spec.ts
  sites/public/cypress/integration/pages/submit-application.spec.ts
  sites/public/lib/HorizontalScrollSection.tsx
Labels: needs review(s)

#1287 1286/mobile filter buttons
  ui-components/src/overlays/Overlay.scss
Labels: ready to merge

#1295 fix: check for existing marketing season
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
Labels: ready to merge
