Repository CityOfDetroit/bloom, pull requests merged in 2022-03, with the labels that each got.

#1021 feat: hides/prevents partner publish
  backend/core/src/auth/authz_policy.csv
  backend/core/src/auth/dto/user-create.dto.ts
  backend/core/src/auth/dto/user-update.dto.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/listings.service.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/Aside.tsx
Labels: needs review(s)

#1023 feat: occupancy table based on unit groups
  backend/core/scripts/import-helpers.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts
  shared-helpers/__tests__/occupancyFormatting.test.tsx
  shared-helpers/src/occupancyFormatting.tsx
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/helpers/tableSummaries.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1022 feat: adds programs to Detroit
  backend/core/src/auth/passport-strategies/jwt.strategy.ts
  backend/core/src/migration/1646422264825-addCommunityPrograms.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/ListingView.tsx
  ui-components/src/blocks/InfoCard.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1019 987/import listings basic
  .gitignore
  backend/core/jest.json
  backend/core/package.json
  backend/core/scripts/import-listings-basic.ts
  backend/core/scripts/import-listings-from-csv.ts
  backend/core/scripts/import-realpages-availability-report.ts
  backend/core/src/auth/passport-strategies/jwt.strategy.ts
  backend/core/src/auth/services/user.service.spec.ts
  backend/core/src/listings/entities/listing-features.entity.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
  backend/core/src/migration/1646422264825-addCommunityPrograms.ts
  backend/core/src/migration/1646642069064-add-new-listing-accessibility-features.ts
  backend/core/src/seeder/seed.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-default-seed.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10145.ts
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/units-transformations.spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailPrograms.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/public/page_content/locale_overrides/general.json
  sites/public/src/ListingView.tsx
  ui-components/src/blocks/InfoCard.tsx
  ui-components/src/locales/general.json
  yarn.lock
Labels: needs review(s)

#994 feat: show a11y features on public site
  backend/core/src/listings/views/config.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-treymore.ts
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  sites/public/styles/overrides.scss
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/global/AppearanceTypes.ts
  ui-components/src/global/blocks.scss
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/text/Description.scss
  ui-components/src/text/Description.tsx
  ui-components/src/text/Tag.scss
Labels: needs review(s)

#1024 992/public primary unit group
  backend/core/scripts/import-helpers.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/seeder/seeds/ami-charts/HUD-MSHDA2021.ts
  backend/core/src/seeder/seeds/ami-charts/HUD-MSHDA2021.txt
  backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts
  backend/core/src/shared/unit-transformation-helpers.spec.ts
  backend/core/src/shared/unit-transformation-helpers.ts
  backend/core/src/shared/units-transformations.spec.ts
  backend/core/src/shared/units-transformations.ts
  backend/core/src/units/types/household-max-income-columns.ts
  backend/core/src/units/types/household-max-income-summary.ts
  backend/core/src/units/types/unit-group-summary.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/locales/general.json
  ui-components/src/sections/ListSection.tsx
Labels: needs review(s)

#1032 fix: add hearing mobility visual to a11y features
  shared-helpers/src/formKeys.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingFeatures.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1035 fix: hide hmi link if no hmi table
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#1030 feat: catch up for migrations
  backend/core/src/migration/1646872355286-catch-up.ts
Labels: needs review(s)

#1038 fix: fix for when rent range was empty
  backend/core/src/shared/units-transformations.ts
Labels: needs review(s)

#1039 fix: styling issues in features section
  sites/public/src/ListingView.tsx
  ui-components/src/page_components/listing/AdditionalFees.tsx
  ui-components/src/text/Description.scss
Labels: needs review(s)

#1040 fix: preview close alert style fixes
  sites/public/pages/preview/listings/[id].tsx
  ui-components/src/notifications/AlertBox.scss
  ui-components/src/notifications/AlertBox.tsx
Labels: needs review(s)

#1042 fix: stray zero if no programs
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#1041 fix: pagination fix for partner listing grid
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
Labels: needs review(s)

#1047 1045/allows re-request confirmation on partners
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/shared/filters/catch-all-filter.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/users/FormUserConfirm.tsx
  sites/partners/src/users/FormUserManage.tsx
  sites/partners/src/users/ReRequestConfirmation.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1051 2022-03-15 release
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/shared/filters/catch-all-filter.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/users/FormUserConfirm.tsx
  sites/partners/src/users/FormUserManage.tsx
  sites/partners/src/users/ReRequestConfirmation.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1057 fix: linting fixes
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/auth/services/user.service.ts
  sites/partners/src/users/FormUserConfirm.tsx
  sites/partners/src/users/ReRequestConfirmation.tsx
Labels: needs review(s)

#1063 fix: fixes pagination issue on detroit user grid
  backend/core/src/auth/services/user.service.ts
Labels: bug, needs review(s)

#1050 feat(backend): update listing filters
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/dto/listing-filter-params.ts
  backend/core/src/listings/types/listing-filter-keys-enum.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/query-filter/index.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/filterUrlLink.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/src/helpers/filters.ts
Labels: needs review(s), needs changes

#1067 feat: Update listing table columns
  sites/partners/pages/index.tsx
  sites/public/lib/helpers.tsx
  ui-components/src/global/vendor/AgPagination.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1088 fix: change verified string
  ui-components/src/locales/general.json
Labels: needs review(s)

#1087 feat(backend): add marketingType to Listing entity
  backend/core/archer.ts
  backend/core/scripts/import-listings-from-csv.ts
  backend/core/scripts/import-listings-from-detroit-arcgis.ts
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/dto/listing-filter-params.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/types/listing-filter-keys-enum.ts
  backend/core/src/listings/types/listing-marketing-type-enum.ts
  backend/core/src/migration/1648548425458-add-listing-marketing.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10145.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10147.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10151.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10153.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10154.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10155.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10157.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10158.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10159.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10168.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10169.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10202.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-treymore.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/src/sms/services/sms.service.spec.ts
  backend/core/src/translations/services/translations.service.spec.ts
  backend/core/test/listings/listings.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/listings/PaperListingForm/formTypes.ts
Labels: ready to merge
