Repository CityOfDetroit/bloom, pull requests merged in 2022-04, with the labels that each got.

#1068 fix: verify link should work on second application tab
  sites/partners/src/listings/PaperListingForm/index.tsx
Labels: needs review(s)

#1069 feat: exposing leasing company website
  backend/core/src/listings/entities/listing.entity.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
  sites/partners/src/listings/PaperListingDetails/sections/helpers.ts
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1077 feat: adds unit summaries to listings list to backend
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10151.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10153.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10154.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10155.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10157.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10158.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10159.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10168.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10169.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10202.ts
  backend/core/src/shared/units-transformations.ts
  backend/core/src/units-summary/dto/unit-group.dto.ts
  backend/core/src/units-summary/entities/unit-group.entity.ts
  backend/core/src/units/types/unit-summaries.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/lib/helpers.ts
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/public/pages/index.tsx
Labels: ready to merge

#1089 78/favorites refactor test2
  backend/core/src/auth/auth.module.ts
  backend/core/src/auth/authz_policy.csv
  backend/core/src/auth/controllers/user-preferences.controller.ts
  backend/core/src/auth/dto/user-basic.dto.ts
  backend/core/src/auth/dto/user-preferences.dto.ts
  backend/core/src/auth/dto/user-profile.dto.ts
  backend/core/src/auth/dto/user.dto.ts
  backend/core/src/auth/entities/user-preferences.entity.ts
  backend/core/src/auth/entities/user.entity.ts
  backend/core/src/auth/guards/user-preferences-authz.guard.ts
  backend/core/src/auth/services/user-preferences.services.ts
  backend/core/src/auth/services/user.service.ts
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/dto/listing-filter-params.ts
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/types/listing-filter-keys-enum.ts
  backend/core/src/migration/1640878095625-favoriteID.ts
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/query-filter/index.ts
  backend/core/src/user-preferences/dto/user-preferences.dto.ts
  backend/core/src/user-preferences/entities/user-preferences.entity.ts
  backend/core/test/user/user-preferences.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/cypress/support/index.d.ts
  sites/public/lib/helpers.tsx
  sites/public/pages/account/dashboard.tsx
  sites/public/pages/account/favorites.tsx
  sites/public/pages/listing/[id]/[slug].tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/ListingCard.test.tsx
  ui-components/index.ts
  ui-components/src/actions/FavoriteButton.tsx
  ui-components/src/authentication/AuthContext.ts
  ui-components/src/global/vendor/AgPagination.tsx
  ui-components/src/helpers/filters.ts
  ui-components/src/icons/Icon.scss
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/locales/general.json
  ui-components/src/page_components/listing/ListingCard.scss
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: ready to merge

#1112 feat: Remove signup subscription fields
  sites/public/pages/account/edit.tsx
  sites/public/pages/create-account.tsx
Labels: needs review(s)

#1118 feat: Add summary tables into the listing
  sites/public/lib/helpers.tsx
Labels: needs review(s)

#1133 fix: about page content edit and margin top and bottom fix
  sites/public/pages/about.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: ready to merge

#1128 feat: can add a marketing status to a listing in partners
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/types/listing-season-enum.ts
  backend/core/src/migration/1649374032458-marketing-season.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/DatesFormatter.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1139 fix: fix migration to check for new object
  backend/core/src/migration/1649709708991-detroit-email-updates.ts
Labels: needs review(s)

#1131 feat: update summary tables and tags with coming soon (1076) (1098) (1074)
  backend/core/src/listings/views/config.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10155.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/public/lib/helpers.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1113 feat: Add .5 and 1.5 bathroom options to min and max dropdown in Add …
  backend/core/src/migration/1649273182040-updated-integer-listing-fields-to-numeric.ts
  backend/core/src/units-summary/entities/unit-group-ami-level.entity.ts
  backend/core/src/units-summary/entities/unit-group.entity.ts
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
Labels: ready to merge

#1156 fix: adds check for unitSummaries?.unitGroupSummary on listing
  sites/public/lib/helpers.tsx
  sites/public/pages/listings.tsx
Labels: ready to merge

#1146 feat: show tags on listing cards for community programs, a11y
  backend/core/src/listings/views/config.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts
  sites/public/lib/helpers.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/page_components/listing/ListingCard.tsx
Labels: needs review(s), discussion

#1137 Feature/region enum
  backend/core/src/listings/dto/listing.dto.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/cypress/fixtures/listing.json
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailBuildingDetails.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/sections/BuildingDetails.tsx
  ui-components/src/sections/GridSection.tsx
Labels: needs changes

#1154 fix: update styling of coming soon tag
  backend/core/src/listings/views/config.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/public/lib/helpers.tsx
  sites/public/pages/index.tsx
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/icons/Icons.tsx
  ui-components/src/locales/general.json
Labels: needs review(s)

#1157 1091/listing sort order
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/types/listing-orderby-enum.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/hooks.ts
  sites/public/pages/listings.tsx
  sites/public/pages/listings/filtered.tsx
Labels: needs review(s)

#1159 fix: wrap DashBlock anchor tag in Link component to display selected …
  ui-components/src/blocks/DashBlock.tsx
Labels: needs review(s)

#1134 feat: updated content & styles on homepage, footer
  sites/public/layouts/application.tsx
  sites/public/lib/HorizontalScrollSection.module.scss
  sites/public/page_content/locale_overrides/general.json
  sites/public/pages/index.module.scss
  sites/public/pages/index.tsx
  sites/public/public/images/hero-placeholder.jpg
  sites/public/styles/actions.scss
  sites/public/styles/blocks.scss
  sites/public/styles/footers.scss
  sites/public/styles/forms.scss
  sites/public/styles/headers.scss
  sites/public/styles/listings.scss
  sites/public/styles/overlays.scss
  sites/public/styles/overrides.scss
  ui-components/src/headers/Hero.tsx
  ui-components/src/helpers/regionNeighborhoodMap.ts
Labels: needs review(s)

#1155 1115/min max validation
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
  ui-components/src/locales/general.json
Labels: ready to merge

#1160 fix: error when passing empty string as phone number to usToIntlPhone…
  sites/public/lib/helpers.tsx
  sites/public/pages/create-account.tsx
Labels: needs review(s)

#1170 fix: coming soon tag color on listing detail page
  sites/public/src/ListingView.tsx
Labels: needs review(s)

#1171 fix: cannot update waitlist status to open
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
Labels: needs review(s)

#1173 feat: add new sign up link to home page
  sites/public/pages/index.tsx
  ui-components/src/actions/LinkButton.tsx
Labels: needs review(s)

#1178 style: add void before trigger functions to avoid eslint errors
  sites/partners/src/listings/PaperListingForm/UnitsSummaryForm.tsx
Labels: needs review(s)

#1166 style: Arabic RTL layout changes
  sites/public/src/ListingView.tsx
  ui-components/src/blocks/ImageCard.scss
  ui-components/src/headers/PageHeader.scss
  ui-components/src/page_components/listing/ListingDetails.tsx
Labels: ready to merge

#1175 1096/tooltip
  sites/public/lib/helpers.tsx
  ui-components/__tests__/blocks/Tooltip.test.tsx
  ui-components/index.ts
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/blocks/Tooltip.scss
  ui-components/src/blocks/Tooltip.stories.tsx
  ui-components/src/blocks/Tooltip.tsx
  ui-components/src/icons/Icon.tsx
  ui-components/src/locales/general.json
  ui-components/src/tables/GroupedTable.tsx
  ui-components/src/tables/StandardTable.tsx
  ui-components/src/text/Tag.tsx
Labels: discussion

#1138 1058/updated public listing filters
  backend/core/src/listings/dto/filter-type-to-field-map.ts
  backend/core/src/listings/dto/listing-filter-params.ts
  backend/core/src/listings/dto/listings-metadata.dto.ts
  backend/core/src/listings/listings.controller.ts
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/types/listing-filter-keys-enum.ts
  backend/core/src/shared/query-filter/custom_filters.ts
  backend/core/src/shared/query-filter/index.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/page_content/locale_overrides/general.json
  sites/public/pages/listings.tsx
  sites/public/pages/listings/filtered.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  ui-components/__tests__/helpers/filters.test.ts
  ui-components/src/actions/Button.tsx
  ui-components/src/blocks/ViewItem.tsx
  ui-components/src/forms/Field.tsx
  ui-components/src/global/blocks.scss
  ui-components/src/helpers/filters.ts
  ui-components/src/helpers/regionNeighborhoodMap.ts
  ui-components/src/icons/Icon.scss
  ui-components/src/icons/Icons.tsx
  ui-components/src/locales/general.json
  ui-components/src/overlays/Drawer.scss
  ui-components/src/overlays/Drawer.tsx
Labels: ready to merge

#1177 1083/header hover issues
  sites/public/styles/headers.scss
Labels: ready to merge

#1195 fix: add leasing agent address field back to listing form
  sites/partners/src/listings/PaperListingForm/sections/LeasingAgent.tsx
Labels: needs review(s)

#1145 feat: default what to expect text and additional what to expect field
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/migration/1649893064530-add-what-to-expect-additional-text.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10136.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10145.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10147.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10151.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10153.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10154.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10155.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10157.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10158.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10159.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10168.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10169.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-10202.ts
  backend/core/src/seeder/seeds/listings/listing-detroit-treymore.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/public/src/ListingView.tsx
  ui-components/__tests__/page_components/WhatToExpect.test.tsx
  ui-components/src/page_components/listing/listing_sidebar/LeasingAgent.tsx
  ui-components/src/page_components/listing/listing_sidebar/ListingUpdated.tsx
  ui-components/src/page_components/listing/listing_sidebar/ReferralApplication.tsx
  ui-components/src/page_components/listing/listing_sidebar/SidebarAddress.tsx
  ui-components/src/page_components/listing/listing_sidebar/Waitlist.tsx
  ui-components/src/page_components/listing/listing_sidebar/WhatToExpect.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/DownloadLotteryResults.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/EventDateSection.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/LotteryResultsEvent.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/OpenHouseEvent.tsx
  ui-components/src/page_components/listing/listing_sidebar/events/PublicLotteryEvent.tsx
Labels: ready to merge, discussion

#1197 fix: authservice.token data null issue (#2703)
  backend/core/src/auth/controllers/auth.controller.ts
  backend/core/src/auth/dto/token.dto.ts
  backend/core/types/src/backend-swagger.ts
Labels: ready to merge

#1209 fix: show street2 for addresses
  ui-components/__tests__/page_components/GetApplication.test.tsx
  ui-components/__tests__/page_components/SubmitApplication.test.tsx
  ui-components/src/helpers/address.tsx
Labels: ready to merge

#1210 feat: set default what to expect text for coming soon listings
  backend/core/src/migration/1651191466791-add-what-to-expect-additional-text-for-coming-soon.ts
Labels: needs review(s)

#1216 fix: remove link to eligibility calculator
  sites/public/layouts/application.tsx
  sites/public/pages/listings.tsx
  sites/public/pages/listings/filtered.tsx
Labels: ready to merge

#1212 fix: Fix tooltip visibility
  sites/public/lib/helpers.tsx
Labels: needs review(s)

#1211 Removes listing queue imports
  backend/core/src/listings/listings.module.ts
  backend/core/src/listings/listings.service.ts
Labels: ready to merge

#1214 1073/coming soon filter
  backend/core/src/shared/query-filter/custom_filters.ts
  sites/public/pages/index.tsx
  sites/public/src/forms/filters/FilterForm.tsx
Labels: ready to merge
