Repository CityOfDetroit/bloom, pull requests merged in 2022-10, with the labels that each got.

#1465 fix: allow deletion of users
  backend/core/src/activity-log/interceptors/activity-log.interceptor.ts
  backend/core/src/applications/applications.controller.ts
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/test/applications/applications.e2e-spec.ts
  backend/core/test/authz/authz.e2e-spec.ts
  backend/core/test/user/user.e2e-spec.ts
  backend/core/types/src/backend-swagger.ts
  sites/partners/src/users/FormUserManage.tsx
Labels: ready to merge

#1468 chore: standardize the typescript version (#3086)
  backend/core/package.json
  package.json
  sites/partners/package.json
  sites/public/package.json
  ui-components/package.json
  yarn.lock
Labels: ready to merge

#1463 1442/listing finder q3
  sites/public/page_content/locale_overrides/general.json
  sites/public/pages/finder.tsx
  sites/public/src/forms/filters/FilterForm.tsx
  sites/public/src/forms/finder/FinderDisclaimer.tsx
  sites/public/src/forms/finder/FinderMultiselect.tsx
  sites/public/src/forms/finder/FinderRentalCosts.tsx
  sites/public/styles/forms.scss
Labels: ready to merge

#1472 1444+5/listing finder q4+5
  sites/public/page_content/locale_overrides/general.json
  sites/public/pages/finder.tsx
  sites/public/src/forms/finder/FinderDisclaimer.tsx
  sites/public/src/forms/finder/FinderMultiselect.tsx
  sites/public/src/forms/finder/FinderRentalCosts.tsx
Labels: ready to merge

#1476 1449/filter no results
  sites/public/pages/listings/filtered.tsx
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/general.json
Labels: blocked by question

#1473 1460/listing finder translations
  sites/public/page_content/locale_overrides/ar.json
  sites/public/page_content/locale_overrides/bn.json
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  sites/public/page_content/resources/housing_glossary.md
  sites/public/pages/finder.tsx
  sites/public/pages/index.tsx
  sites/public/src/forms/finder/FinderRentalCosts.tsx
  sites/public/styles/headers.scss
  ui-components/src/locales/ar.json
  ui-components/src/locales/bn.json
  ui-components/src/locales/es.json
  ui-components/src/locales/general.json
Labels: 1 review needed

#1467 1458/neighborhood amenities partners
  sites/partners/cypress/fixtures/listing.json
  sites/partners/cypress/integration/listing.spec.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/partners/pages/listings/[id]/index.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailNeighborhoodAmenities.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/NeighborhoodAmenities.tsx
  ui-components/src/locales/general.json
Labels: ready to merge
